### ISSUE TITLE
Feedback sobre as categorias das postagens/denúncias

### ISSUE THREAD

**Issue by Mateusas3s** [fga-eps-mds/2020.1-VC_Usuario#108]
### Descrição:
Solicitei ao Fernando do DAF as categorias mais recorrentes das questões a serem resolvidas na UnB.
Segue abaixo um print da resposta.

![img-email](https://user-images.githubusercontent.com/18116735/94443476-9954aa80-017b-11eb-9968-8922f1c232d2.jpeg)

**Comment by Bruno-Felix** [comment]
Opa. Iremos já usar essa base de Categorias para a criação de postagens.
