### ISSUE TITLE
Revisão de documentação

### ISSUE THREAD

**Issue by enzoggqs** [fga-eps-mds/2020.1-VC_Usuario#111]
### Descrição:
Os integrantes do grupo irão revisar todos os documentos feios no projeto até o momento, e farão modificações se necessário.

### Tarefas:
Revisão dos documentos:

- [x] Documento de Visão;*
- [x] Documento de Arquitetura;*
- [x] Gerenciamento do plano de riscos;
- [x] Product Backlog;*
- [x] Roadmap;*
- [x] Templates;
- [x] CONTRIBUITING;
- [x] Readme;
- [x] Políticas;*
- [x] Sprints;
- [x] CODE_OF_CONDUCT.
- ***É CRUCIAL VER SE O DOCUMENTO NA BRANCH DE REVISÃO ESTÁ PARALELAMENTE ATUALIZADA EM RELAÇÃO A DEVELOP**

### Critérios de aceitação:

- [x] Revisão de todos os documentos citados acima.
- [x] Todos o documentos revisados estarem disponíveis na página de documentação.

**Comment by DenysRogeres** [comment]
Acabei de revisar o Product Backlog e acredito que o documento esteja bem feito, contudo, verifiquei que faltou fazer o Planning Poker nas user stories que foram adicionadas recentemente. Creio que uma coluna "Status" acrescentaria muito na também.

**Comment by DanielPortods** [comment]
@DenysRogeres Fiz algumas alterações nos docs das sprints. No preview da gh-pages, as imagens importadas pela tag <img> não eram carregadas. Sendo assim, mudei a implementação para markdown. 
Além disso, vi alguns erros de coloração dos campos na tabela de conhecimentos da Sprint 2. Sugiro que revise todas as tabelas para corrigir possíveis erros semelhantes. 

**Lembrando que eu renomeei a branch de revisão, tomem cuidado com o repositório local dos senhores.**

**Comment by DenysRogeres** [comment]
> @DenysRogeres Fiz algumas alterações nos docs das sprints. No preview da gh-pages, as imagens importadas pela tag  não eram carregadas. Sendo assim, mudei a implementação para markdown.
> Além disso, vi alguns erros de coloração dos campos na tabela de conhecimentos da Sprint 2. Sugiro que revise todas as tabelas para corrigir possíveis erros semelhantes.
> 
> Lembrando que eu renomeei a branch de revisão, tomem cuidado com o repositório local dos senhores.

Ótima observação @DanielPortods, acabei de corrigir o quadro de conhecimentos da Sprint 2 e fiz uma correção na formatação da Sprint 5 na sidebar

**Comment by DanielPortods** [comment]
Fiz os caminhos para os documentos de políticas ficarem acessíveis pela página de documentação. Acredito que o Readme da branch develop/master deve direcionar, na parte de politicas, para a página das políticas na gh-page.
