### ISSUE TITLE
Produção da apresentação para a R1

### ISSUE THREAD

**Issue by DenysRogeres** [fga-eps-mds/2020.1-VC_Usuario#114]
### Descrição:
Os integrantes devem produzir todo o material necessário para a apresentação na Release 1.

### Tarefas:

- [x] Criar material para apresentação.
- [x] Reunir grupo no streamyard para produção do vídeo.

### Critérios de aceitação:

- [x] Todo o material da apresentação estar completo.
- [x] Video presente no README e em comentário na issue 79 do repositório da disciplina.
- [x] Slide presente no README.

**Comment by DenysRogeres** [comment]
Acabei de criar uma conta no Stremyard, acredito que se fizemos a transmissão direto pro youtube será mais fácil, uma vez que está transmissão fica gravado. Caso necessário, podemos baixar o vídeo e fazer os devidos cortes.

**Comment by DanielPortods** [comment]
Vamos nos atentar a issue [#79](https://github.com/fga-eps-mds/A-Disciplina/issues/79).

**Comment by DanielPortods** [comment]
@DenysRogeres todos precisam ter uma conta no streamyard ou somente quem vai fazer a gravação?

**Comment by DenysRogeres** [comment]
> @DenysRogeres todos precisam ter uma conta no streamyard ou somente quem vai fazer a gravação?

Somente quem vai fazer a gravação (no caso eu), vocês só vão precisar entrar através do link e colocar o nome.
