### ISSUE TITLE
Estudo sobre segurança

### ISSUE THREAD

**Issue by DanielPortods** [fga-eps-mds/2020.1-VC_Usuario#131]
### Descrição:

Com o objetivo de implementar mecânicas de segurança no sistema nas próximas Sprints, todos os integrantes devem realizar estudo sobre o tema e compartilhar o conhecimento.
### Tarefas:

- [x] Estudar sobre segurança nas comunicações internas e externas (API);
- [x] Estuda sobre tokens e autenticações;
- [ ] Ver implementações de outros projetos.
### Critérios de aceitação:

- [x] Compartilhar as melhores fontes por essa issue.

**Comment by emysdias** [comment]
![image](https://user-images.githubusercontent.com/52640974/95782103-8676c580-0ca5-11eb-98b3-15a47c6ae659.png)

Com funciona o JWT

**Comment by emysdias** [comment]
![image](https://user-images.githubusercontent.com/52640974/95782513-61368700-0ca6-11eb-8c74-f7c6932437f8.png)

Vi sobre essas dependências que podem ser interessantes

**Comment by emysdias** [comment]
https://imasters.com.br/back-end/trabalhando-autenticacao-com-jwt-e-vue-2

Tem esse link com o jwt no vue.js

**Comment by DanielPortods** [comment]
É interessante conhecermos os status codes possíveis e o que eles significam na resposta de uma requisição HTTP.
Os erros são importantes na comunicação da plataforma.
Esse [link](https://developer.mozilla.org/pt-BR/docs/Web/HTTP/Status) explica bem a padronização.

**Comment by DanielPortods** [comment]
Estamos utilizando o axios na comunicação entre front e back e acho que seria interessante termos a noção da [documentação](https://www.npmjs.com/package/axios#request-config). 
Principalmente no atributo request-config.
Vale mostrar uma mecânica do axios que consiste em filtrar os status das respostas HTTP no intervalo **status >= 200 && status < 300**.

**Comment by DanielPortods** [comment]
Muitos dos problemas de segurança podem ser evitados com a correta utilização do [Cors](https://developer.mozilla.org/pt-BR/docs/Web/HTTP/Controle_Acesso_CORS).
No momento, a nassa plataforma permite qualquer acesso, o nosso Cors não está tabalhado. Sendo assim, vale destacar a [documentação](https://www.npmjs.com/package/cors) da funcionalidade do node que trabalha o Cors.
