### ISSUE TITLE
Code climate e integrar ao repositório

### ISSUE THREAD

**Issue by emysdias** [fga-eps-mds/2020.1-VC_Usuario#141]
### Descrição:
Usar o code climate no projeto

### Tarefas:
- [x]  Usar o code climate

### Critérios de aceitação:
- [x] Integrar o code climate ao projeto

**Comment by emysdias** [comment]
![image](https://user-images.githubusercontent.com/52640974/96356555-8b34e280-10c6-11eb-8a67-b294c770be97.png)

Fui adicionar o repositório do front mas o code climate não suporta, só deu certo no back

**Comment by emysdias** [comment]
![image](https://user-images.githubusercontent.com/52640974/96356588-f7174b00-10c6-11eb-8982-77894ad65678.png)

E esse aqui é o do back-end

**Comment by emysdias** [comment]
![image](https://user-images.githubusercontent.com/52640974/96356599-20d07200-10c7-11eb-9793-261c52838f77.png)

Essa é a duplicação que ele está reclamando

**Comment by enzoggqs** [comment]
Nosso code smells está 0, isso é um ponto positivo do nosso trabalho!! 🏆🏆

**Comment by enzoggqs** [comment]
temos uma duplicação de código que deve ser resolvida 😧😧

**Comment by emysdias** [comment]
![image](https://user-images.githubusercontent.com/52640974/96356677-70636d80-10c8-11eb-980a-b1c7d527c4e1.png)

Foi integrado os nossos repositórios

**Comment by DanielPortods** [comment]
Acho que falta alguma coida no README para acessar essa plataforma.

**Comment by DanielPortods** [comment]
Vi no repositório do [Acácia](https://github.com/fga-eps-mds/2019.2-Acacia), por exemplo, que tem um botão no README contendo o maintainability e que redireciona para a plataforma.
