### ISSUE TITLE
Desenvolver Testes - Back-end

### ISSUE THREAD

**Issue by DanielPortods** [fga-eps-mds/2020.1-VC_Usuario#162]
### Descrição:

Deve ser desenvolvida uma boa cobertura de testes para os métodos do back-end.

### Tarefas:
- [x] Resolver o problema na utilização do Jest;
- [x] Criar testes para os métodos de postagem;
- [x] Criar testes para os métodos de usuário; 
- [x] Criar testes para os métodos de UPS 

### Critérios de aceitação:

- [x] Métodos terem ao menos um teste desenvolvido.

**Comment by Bruno-Felix** [comment]
Tive problemas de que as dependências não estão sendo reconhecidas nos arquivos .tests

**Comment by Bruno-Felix** [comment]
Temos com conectar os testes as rotas e ao banco de dados de forma correta.

**Comment by Bruno-Felix** [comment]
Criei os testes básicos dos métodos da user_controller.
