### ISSUE TITLE
Levantar pontuação das ações na aplicação

### ISSUE THREAD

**Issue by DanielPortods** [fga-eps-mds/2020.1-VC_Usuario#163]
### Descrição:
Issue destinada ao levantamento e decisão das pontuações que o usuário irá receber por cada ação na aplicação.

**Reunião feita segunda, 02/11**

### Tarefas:
- [x] Todos os integrantes devem comentar as ações que devem ser "remuneradas" e suas respectivas pontuações;
- [x] Quando todos completarem a tarefa acima, devemos debater sobre tudo levantado numa daily.

### Critérios de aceitação:
- [x] Todos os levantamentos serem feitos pelos integrantes;
- [x] Todos os levantamentos serem debatidos pelos integrantes;
- [x] As ações "remuneradas" e  suas pontuações serem devidamente definidas.

**Comment by Bruno-Felix** [comment]
Ações e Pontuação:

- Cadastrar: 200 pontos
- Criar Postagem; 500 pontos
- Apoiar Postagem; 50 pontos
- Comentar Postagem; 30 pontos
- Postagem reportada ser verificada como inadequada: 150 pontos
- Postagem postada ser verificada como resolvida: 200 pontos

**Comment by DanielPortods** [comment]
> Minhas Ações e Pontuação:
> 
> * Cadastrar: 300 pontos
> * Criar Postagem; 150 pontos
> * Apoiar Postagem; 50 pontos
> * Comentar Postagem; 30 pontos
> * Postagem reportada ser verificada como inadequada: 200 pontos
> * Postagem postada ser verificada como resolvida: 400 pontos

Achei massa. Só mudaria a pontuação por criação da postagem, acho que deveria ser menor para somente a criação do registro e, caso houver mudança de status de "aguardando" para "em andamento", ser acrescentado mais pontos pro autor.
Também acho que o autor possa pontuar de acordo com o engajamento na postagem criada com uma pontuação menor, claro.
Por exemplo: 5 pts o apoio e 7 pts o comentário.

**Comment by emysdias** [comment]
> Minhas Ações e Pontuação:
> 
>     * Cadastrar: 300 pontos;
> 
>     * Apoiar Postagem; 10 pontos;
> 
>     * Criar Postagem; 100 pontos;
> 
>     * Em Andamento: 100;
> 
>     * Postagem postada ser verificada como resolvida: 400 pontos.

Concordo com as pontuações!!

**Comment by daniel-bm** [comment]
> Minhas Ações e Pontuação:
> 
> * Cadastrar: 300 pontos;
> * Apoiar Postagem; 10 pontos;
> * Criar Postagem; 100 pontos;
> * Em Andamento: 100;
> * Postagem postada ser verificada como resolvida: 400 pontos.

Acho que está bom assim.

**Comment by enzoggqs** [comment]
> Ações e Pontuação Decididas na Reunião segunda, 02/11:
> 
> * Cadastrar: 300 pontos;
> * Apoiar Postagem; 10 pontos;
> * Criar Postagem; 100 pontos;
> * Em Andamento: 100;
> * Postagem postada ser verificada como resolvida: 400 pontos.

Concordo!!

**Comment by DenysRogeres** [comment]
> Minhas Ações e Pontuação:
> 
> * Cadastrar: 300 pontos;
> * Apoiar Postagem; 10 pontos;
> * Criar Postagem; 100 pontos;
> * Em Andamento: 100;
> * Postagem postada ser verificada como resolvida: 400 pontos.

Ficou perfeito a pontuação, acho que está bem coerente! Só faltou a parte da quantificação, exemplo "a cada 7 apoiar postagem você ganha 10 pontos", mas como demonstração tá perfeito.

**Comment by DanielPortods** [comment]
> Ações e Pontuação Decididas na Reunião segunda, 02/11:
> 
> * Cadastrar: 300 pontos;
> * Apoiar Postagem; 10 pontos;
> * Criar Postagem; 100 pontos;
> * Em Andamento: 100;
> * Postagem postada ser verificada como resolvida: 400 pontos.

Concordo também!
