### ISSUE TITLE
Estudar implementação de PWA

### ISSUE THREAD

**Issue by enzoggqs** [fga-eps-mds/2020.1-VC_Usuario#165]
### Descrição:
Os responsáveis devem estudar sobre a implementação de PWA, e seus subtópicos para serem batedores dos demais membros do grupo
### Tarefas:

- [x]  Estudo da implementação de PWA 

### Critérios de aceitação:

- [x] Os responsáveis terem estudado sobre, e estarem prontos para compartilhar o conhecimento com os demais membros

**Comment by enzoggqs** [comment]
Li essa [página](https://klickpages.com.br/blog/push-notification/) pra me introduzir no conteúdo de push notifications e vi esse [vídeo](https://www.youtube.com/watch?v=MZV_wE6_EGw) que mostra como implementar push notifications na pwa

**Comment by DenysRogeres** [comment]
Li alguns artigos e assisti alguns vídeos e vou fazer uma síntese de tudo.

Há alguns requisitos para o PWA, dentre eles estão:
- Ser seguro e servido via HTTPS;
- Progressivo, ou seja, funcionar em múltiplos navegadores;
- Ter acesso OFFLINE (retornar pelo menos a URL principal offline);
- Responsivo, disponível para qualquer device;
- APP LIKE (usuário ter a sensação de estar em um app nativo);
- Instalável (adicionar à home screen);
- Atualizado (browser deve detectar atualização e instalá-las quando necessário);

Essa lista pode ser acessada de forma completa no [artigo](https://web.dev/pwa-checklist/) da Google, na qual está disposto todo o checklist. Para verificar se estamos cumprindo com todos os requisitos, podemos usar a ferramenta open-source [Lighthouse](https://developers.google.com/web/tools/lighthouse/) disponibilizado também pela Google que executará uma série de testes na página e gerará um relatório sobre o desempenho da página. Nesse relatório, nós poderemos usar os testes que apresentaram falha como indicadores do que pode ser feito para aprimorar a PWA.

**Comment by DenysRogeres** [comment]
Para fazer push notifications, ser instalável e ter atualizações automáticas precisamos mexer com o <b>Service Worker</b> que é o core de uma aplicação PWA. Service worker é um script que seu navegador executa em segundo plano, separado da página da Web. Isso possibilita recursos que não precisam de uma página da Web ou de interação do usuário, ou seja, é uma maneira de dizer para o browser o modo que ele deve agir em determinadas situações.
O passo-a-passo para instalar o service worker pode ser encontrado nessa [página](https://developers.google.com/web/fundamentals/primers/service-workers?hl=pt) onde é descrito gradualmente o que se deve fazer. Nos estudos eu encontrei um [template](https://github.com/vuejs-templates/pwa) para pwa que talvez seja útil.

Vou disponibilizar alguns links apenas para fins de estudo:
[Milene Lacerda - Construindo PWAs com Vue.js - BrazilJS Conf 2017](https://www.youtube.com/watch?v=jdEBLQVZRdo&t=4s)
[O que é PWA e como criar](https://neilpatel.com/br/blog/pwa-o-que-e/)
[PWA Series: Service Workers, the basics about offline](https://medium.com/samsung-internet-dev/pwa-series-service-workers-the-basics-about-offline-a6e8f1d92dfd)
[Como fazer seu site funcionar offline com PWA](https://willianjusten.com.br/como-fazer-seu-site-funcionar-offline-com-pwa/)
[Service Worker](https://www.pwabuilder.com/serviceworker)
[Introduction to Service Worker](https://developers.google.com/web/ilt/pwa/introduction-to-service-worker)
