### ISSUE TITLE
Desenvolver Testes - Front-end

### ISSUE THREAD

**Issue by Bruno-Felix** [fga-eps-mds/2020.1-VC_Usuario#175]
### Descrição:

Deve ser desenvolvida uma boa cobertura de testes para os métodos do front-end.

### Tarefas:
- [ ] Criar testes para os métodos;

### Critérios de aceitação:

- [ ] Métodos terem ao menos um teste desenvolvido.

**Comment by DanielPortods** [comment]
Infelizmente tivemos muita dificuldade com a realização de testes.
Por mais que a equipe entenda a importância dos testes no processo, viu-se que, não mais havendo tempo hábil até a próxima entrega, não foi satisfatória a implementação de testes no front-end da aplicação. 😭 
Sendo assim, por hora encerraremos essa issue com essa dívida imensa para que, quando dada continuidade após a R2, possamos focar mais na testagem.
