### ISSUE TITLE
Padrões PWA

### ISSUE THREAD

**Issue by DenysRogeres** [fga-eps-mds/2020.1-VC_Usuario#176]
### Tarefas:

- [x]  Implementar padrões PWA
- [x] Registro e instalação do service worker
- [x] Configuração do manifest.json

### Critérios de aceitação:

- [x] Dever ser cumprido a checklist de PWA

**Comment by DanielPortods** [comment]
Essa issue tá mal detalhada.

**Comment by DanielPortods** [comment]
Para implementar os padrões de PWA se trabalha muito com alguns aspectos dos navegadores. Vocês viram em algum momento se existe a possibilidade de a plataforma identificar o navegador do usuário? Exemplo: poderiamos definir um id único pra um navegador?

**Comment by DenysRogeres** [comment]
> Para implementar os padrões de PWA se trabalha muito com alguns aspectos dos navegadores. Vocês viram em algum momento se existe a possibilidade de a plataforma identificar o navegador do usuário? Exemplo: poderiamos definir um id único pra um navegador?

Essa etapa de identificação ocorre no registro do service worker. Nessa etapa é verificado se o navegador suporta ou não o service worker, caso isso aconteça, ele registra o service worker e após isso vem a etapa de ativação e instalação.
Contudo a maiores dos navegadores já suportam, isso pode ver verificado neste [site](https://jakearchibald.github.io/isserviceworkerready/).
