### ISSUE TITLE
Desenvolvimento e atualização de documentação

### ISSUE THREAD

**Issue by DenysRogeres** [fga-eps-mds/2020.1-VC_Usuario#177]
### Tarefas:

- [x]  Documentação da Sprint 10;
- [x] Levantamento de mudanças de arquitetura;
- [x] Atualização e correção do roadmap.

### Critérios de aceitação:

- [x] A docuementacão da sprint 10 estar completa;
- [x] O Roadmap estar atualizado, corrigido e devidamente revisado;
- [x] Serem levantados pontos do projeto até então desenvolvido que não seguem o planejamento inicial da arquitetura.

**Comment by DanielPortods** [comment]
Levantamento de desvios do planejamente arquitetural:

- Place e Category inicialmente foram modelados como documentos diferentes, para os quais teriam uma model cada com alguns atributos. Estamos usando category e place somente como um elemento estático na model da postagem;
- O atributo post_permission da model da postagem não será mais utilizado no projeto.
- A modelagem do banco de dados em questão ao apoio das postagens se saiu muito complexa na prática. Por isso, foi preciso adicionar os parametros post_support_number e post_supporting na model das postagens.
- Provavelmente será feita uma refatoração no mecanismo de apoio para substituir a utilização da model UPS por um array de ids de postagens apoiadas na model do user e por um semelhante ao post_support_number na model da postagem.
- Foi adicionado o post_author na postagem para armazenar o nome do autor estaticamente. Porém, essa será uma refatoração a ser feita visto que, ao inserir tal atributo, se acaba com a função da chave estrangeira contendo o id do autor.
- O atributo unique_id da model do uduario não será mais utilizado no projeto.

**Comment by Bruno-Felix** [comment]
> Levantamento de desvios do planejamente arquitetural:
> 
> * Place e Category inicialmente foram modelados como documentos diferentes, para os quais teriam uma model cada com alguns atributos. Estamos usando category e place somente como um elemento estático na model da postagem;
> * O atributo post_permission da model da postagem não será mais utilizado no projeto.
> * A modelagem do banco de dados em questão ao apoio das postagens se saiu muito complexa na prática. Por isso, foi preciso adicionar os parametros post_support_number e post_supporting na model das postagens.
> * Provavelmente será feita uma refatoração no mecanismo de apoio para substituir a utilização da model UPS por um array de ids de postagens apoiadas na model do user e por um semelhante ao post_support_number na model da postagem.
> * Foi adicionado o post_author na postagem para armazenar o nome do autor estaticamente. Porém, essa será uma refatoração a ser feita visto que, ao inserir tal atributo, se acaba com a função da chave estrangeira contendo o id do autor.
> * O atributo unique_id da model do uduario não será mais utilizado no projeto.

A refatoração da model de UPS acredito que seja um processo EXTREMAMENTE difícil hoje.

Só o apoio de postagem passa por diversos métodos que serão modificados ou desfeitos. Além das rotas de editar,  excluir postagem, listagem por categoria que usam um método da controller da UPS para funcionar.

Acredito que no front a maneira que o UPS foi trabalhado precisa mesmo de ser alterada.

Mas no back são diversos arquivos para serem mexidos, diversos métodos  para serem mexidos, diversas rotas para se readequar para, no fim, chegar num resultado igual ou bem semelhante ao que é hoje.

Além de proporcionar ao projeto um estado de "criação" e resolução de erros desnecessária considerando que estamos a menos de um mês do final e  ter muitas outras coisas como prioridade.
