### ISSUE TITLE
Ajustes gerais

### ISSUE THREAD

**Issue by DanielPortods** [fga-eps-mds/2020.1-VC_Usuario#196]
### Descrição:

Devem ser realizados alguns ajustes no projeto visando a entrega para a R2.
### Tarefas:

- [x] Localizar e remover console.log de debug;
- [x] Fazer o texto do botão apoiar se modificar quando clickado;
- [x] Resolver o problema do aviso de senha violada no Chrome;
- [x] Resolver o problema do usuário estar logado em toda a plataforma menos na página de perfil.
- [x] Atualizar nome nos comentários aos editar o nome no perfil.
- [x] Inserir um alert ao criar uma postagem.

### Critérios de aceitação:

- [x] As tarefas estarem concluídas e devidamente revisadas.

**Comment by Bruno-Felix** [comment]
A priri estamos conseguindo visualizar se o usuário está logado, tanto na tela home, tanto na tela de criar postagem.

Parece que esse bug é mais evidente quando usamos o docker e rodamos localmente, percebi que já no deploy atual ele já percebe se está logado ou não em todas as páginas.

**Comment by Bruno-Felix** [comment]
Seria bom dá um pull devel para pegar as mudanças que eu e Emily inserimos no back e no front.

**Comment by Bruno-Felix** [comment]
Galera. Vocês conseguem resolver o bug de quando o nome da pessoa é editado, ele não muda o nome dos seus comentário.

Seria só chamar um método atrás do método update_user_postages_author na rota /user/update/:id que resolve izi.

Ou fazer dentro da update_user_postages_author e mudar seu nome para ficar mais condizente com a ação do método.

Vcs que decidem.

**Comment by DanielPortods** [comment]
Vou dar uma olhada nisso...

**Comment by Bruno-Felix** [comment]
Vocês podem colocar um alert ou model quando uma postagem é criada?! 

Não mexi nisso mas acho que seria interessante.

**Comment by daniel-bm** [comment]
Podemos também acho que seria interessante
