### ISSUE TITLE
Arrumar Bugs na Aplicação

### ISSUE THREAD

**Issue by emysdias** [fga-eps-mds/2020.1-VC_Usuario#197]
### Descrição:
Essa issue vai ser para arrumar algumas coisas que não estão certas no back-end

### Tarefas:
- [x] Criar postagem não anonimo pelo front dá erro.
- [x] Quando o usuário é apagado, o numero de support da postagem não muda;
- [x] Criar postagem pelo back não define o post_author caso o mesmo não venha no req.body;
- [x] Deletar postagem não tira pontuação;
- [x]  Mudar nome do usuário = mudar nome da postagem;
- [x] Deletar Usuário - Apagar UPS, UPC e suas postagens;
- [X] Deletar Postagem - Apagar UPS e UPC;
- [x]  Bug de erro na tentativa de relogar editar postagem;
- [x]  Verificar se usuário existe quando criar postagem; (check_exist_user_and_postage);
- [x]  Bug Criar Postagem Normal sem fk_user_id;
- [x]  Erro de Criar usuário no back pelo back e não conseguir fazer login; (teste);
- [x]  Criar postagem n anonima no back e não conseguir listar no front; (teste);
- [x]  Garantir que o status seja mudado somente para Aguardando e Resolvido; (testar rota); 
- [x]  Verificar métodos obsoletos;
- [ ] find_user faz a mesma coisa do check_user_exist
- [x]  Separar rotas de test e retirar possíveis rotas necessárias;
- [x]  Verificar e retirar na model e no front postage - post_comments, relev_degree, post_permission, post_type;
- [x]  Retirada de uns console.log();
- [x] Tirar array de UPSs do User;
- [x] Erro de listar postagem quando o usuário está logado mais o mesmo não existe. (deveria listar as postagens mesmo dando erro)

### Critérios de aceitação:
- [x] Todas as tarefas serem feitas

**Comment by emysdias** [comment]
nesse aqui "find_user faz a mesma coisa do check_user_exist" fazem a mesma coisa, mas com atributos diferentes

**Comment by Bruno-Felix** [comment]
> nesse aqui "find_user faz a mesma coisa do check_user_exist" fazem a mesma coisa, mas com atributos diferentes, a não ser q coloque essa escolha lá

Então. Podíamos ajustar isso para usar o mesmos atributos e excluir essa repetição.

**Comment by Bruno-Felix** [comment]
@emysdias será que se, quando uma postagem é apagada, os pontos das pessoas que apoiaram e comentaram deve diminuir?

**Comment by emysdias** [comment]
> @emysdias será que se, quando uma postagem é apagada, os pontos das pessoas que apoiaram e comentaram deve diminuir?

acho q não pq a pessoa fez a ação, ai como foi excluido creio q a pessoa não deve perder ponto por isso

**Comment by Bruno-Felix** [comment]
> > @emysdias será que se, quando uma postagem é apagada, os pontos das pessoas que apoiaram e comentaram deve diminuir?
> 
> acho q não pq a pessoa fez a ação, ai como foi excluido creio q a pessoa não deve perder ponto por isso

Justo!
