### ISSUE TITLE
Revisão de documentação

### ISSUE THREAD

**Issue by DanielPortods** [fga-eps-mds/2020.1-VC_Usuario#207]
### Descrição:

A documentação deve ser revisada e atualizada com foco na entrega da release 2.

### Tarefas:

- [x] Inserir a documentação da Sprint 15;
- [x]  Atualizar a documentação com as mudanças desde a R1;
- [x] Inserir o Post Mortem;
- [x] Desenvolver o Post Mortem;
- [x] Colocar nome e descrição nas millestones do projeto e deixar em ordem.

### Critérios de aceitação:

- [x] A página de documentação deve está atualizada e devidamente revisada.

**Comment by Bruno-Felix** [comment]
@DenysRogeres a separação entre cores do Roadmap não ficou muito intuitiva.

Usou um degradê nas Sprints mas nas tarefas deixou a mesma cor(Inclusive um crime de desing branco no amarelo, imagina o mundo dessa imagem sendo projetada na parede de uma sala na FGA. Não ia dá pra ver nada)

**Comment by Bruno-Felix** [comment]
> @DenysRogeres a separação entre cores do Roadmap não ficou muito intuitiva.
> 
> Usou um degradê nas Sprints mas nas tarefas deixou a mesma cor(Inclusive um crime de desing branco no amarelo, imagina o mundo dessa imagem sendo projetada na parede de uma sala na FGA. Não ia dá pra ver nada)
> 
> Também não achei interessante o degradê do verde pro vermelho, dá a sensação que as primeiras sprints são fáceis e leves e as ultimas tem um censo de negatividade e/ou urgência, sendo que não é bem assim, planejamos e seguimos a risca para chegarmos bem sem correr na ultima semana.

kkkkk Sei da onde vc se inspirou nesse Roadmap ai. kkkk

Mano n faz do jeito deles. Fica parecendo cópia.

Faz no mesmo modelo mas usa igual a Gabi disse, uma linha num tom, outra num mais escuro, e assim vai alternando.

**Comment by DenysRogeres** [comment]
> @DenysRogeres a separação entre cores do Roadmap não ficou muito intuitiva.
> 
> Usou um degradê nas Sprints mas nas tarefas deixou a mesma cor(Inclusive um crime de desing branco no amarelo, imagina o mundo dessa imagem sendo projetada na parede de uma sala na FGA. Não ia dá pra ver nada)
> 
> Também não achei interessante o degradê do verde pro vermelho, dá a sensação que as primeiras sprints são fáceis e leves e as ultimas tem um censo de negatividade e/ou urgência, sendo que não é bem assim, planejamos e seguimos a risca para chegarmos bem sem correr na ultima semana.

Ótimas observações @Bruno-Felix, quanta informação contida em apenas uma paleta de cores, jamais teria percebido tudo isso! 
A letra da cor das sprint já foi mudada, apenas não foi atualizada ainda por urgência em outras issues. Em relação ao degradê das sprint, a mesma foi utilizada no [roadmap](https://fga-eps-mds.github.io/2020.1-Minacademy-Wiki/produto/roadmaps/) do minacademy, apenas aproveitei as cores que elas utilizaram, mas não percebi que teve essa sensação sinestésica.
 Mas o documento é do grupo, você pode mudar as cores para as mais adequadas também (lembre-se que daltônicos também irão ter contato), acredito que o link de edição foi enviado para seu email.
