### ISSUE TITLE
Elaborar Apresentação R2

### ISSUE THREAD

**Issue by DanielPortods** [fga-eps-mds/2020.1-VC_Usuario#208]
### Descrição:

A R2 chegou!
### Tarefas:

- [x] Definir o roteiro e esquema de apresentação;
- [x] Montar os Slides;
- [x] Separar as responsabilidades na apresentação;

### Critérios de aceitação:

- [x] Todos os integrantes estarem cientes de suas responsabilidades;
- [x] Os slides estarem a contento.

**Comment by gag2502** [comment]
Critério de aceitação número 3 : Câmera aberta e sorriso no rosto ;-)
