### ISSUE TITLE
Revisar todas as funcionalidades da aplicação

### ISSUE THREAD

**Issue by enzoggqs** [fga-eps-mds/2020.1-VC_Usuario#211]
### Descrição:
Os designados devem testar tudo dentro da aplicação a procura de erros ou bugs uqe ainda existam

### Tarefas:

- [x] Testar as funcionalidades localmente;
- [x] Testar as funcionalidade no deploy;
- [x] Arrumar bugs se necessário;

### Critérios de aceitação:

- [x] Tudo estar funcionando dentro dos conformes

**Comment by Bruno-Felix** [comment]
Vale lembrar da importância de testar todas as funcionalidades:
- Logado;
- Não logado;
- Com o mesmo usuário que criou;
- Com um usuário diferente.

**Comment by Bruno-Felix** [comment]
Incrementa essas tarefas ai, Uma estratégias de teste e não deixar nada para trás é crucial para um bom teste.

**Comment by Bruno-Felix** [comment]
Um ponto interessante é testar apagar/deslogar um usuário no meio de algo de que demande um usuário logado como listar home logado, criar postagem logado, listar uma postagem logado. Ver a reação da página quando faz alguma uma ação como apoiar, comentar ou atualizar a página atual ou  renderizar para outra.
