### ISSUE TITLE
Desenvolver Identidade Visual

### ISSUE THREAD

**Issue by DanielPortods** [fga-eps-mds/2020.1-VC_Usuario#66]
### Descrição:
Desenvolver Identidade Visual da plataforma.

### Tarefas:

- [x] Desenvolver ideias de logomarcas. 

- [x] Sugerir paletas de cores.

- [x] Guia de cores, fontes e botões

### Critérios de aceitação:

- [x] Realizar reunião para discutir as tarefas.

- [x] Definir o conjunto completo de estilo do projeto.

**Comment by DanielPortods** [comment]
### Tentei idealizar alguns esboços de logomarcas:

![logos](https://user-images.githubusercontent.com/48573556/93112189-11a47180-f68e-11ea-9b56-f1d6ab04fc17.jpg)

**Ideia 1**: Por mais que se pareça com um lápis, a ideia 1 é uma casa, simbolizando a infraestrutura da UnB e dando uma ideia de proteção, cuidado e segurança.
**Ideia 2**: Seguindo a ideia da proteção e cuidado com a infraestrutura, a ideia 2 é um escudo. Tentei aproveitar o formato da logo da UnB, que é a silhueta do Plano Piloto, para envolver um pouco de identidade nessa ideia. Imaginei esse escudo sendo colorido com as cores da logo da UnB. Ficou um pouco difícil de representar mas acredito que, se vetorizada, pode ficar mais harmônica e bem simétrica.
**Ideia 3**: A Ideia 3 Sugere um muro. Na mesma pegada de infraestrutura, cuidado e proteção.

**Comment by emysdias** [comment]
#66 Sugestões de paleta de cores

![AdobeColor-Summer breeze](https://user-images.githubusercontent.com/52640974/93352964-c6b36700-f811-11ea-9fc2-2d0c81bf2d84.jpeg)

![AdobeColor-A dream comes True!](https://user-images.githubusercontent.com/52640974/93353039-d8950a00-f811-11ea-98a8-bf3ca96663df.jpeg)

**Comment by emysdias** [comment]
#66 Mais duas sugestões, eu to procurando paletas que tenha verde, pois acho que ainda tem que combinar com o verde da UnB, mas achei um sem verde q amei as cores ai vou colocar aqui

![AdobeColor-Character set](https://user-images.githubusercontent.com/52640974/93353343-33c6fc80-f812-11ea-8a48-a05f4eb0b5a2.jpeg)

![AdobeColor-Moti Co  Toothbrush](https://user-images.githubusercontent.com/52640974/93353357-39bcdd80-f812-11ea-8f93-7c2e47bcec61.jpeg)

**Comment by emysdias** [comment]
#66 Fontes de letras (sugestões)

![image](https://user-images.githubusercontent.com/52640974/93354028-f44ce000-f812-11ea-8001-67d94c9f3b05.png)
![image](https://user-images.githubusercontent.com/52640974/93354191-1cd4da00-f813-11ea-8356-1029e4cb37f0.png)

**Comment by emysdias** [comment]
#66 Sugestão de logomarca, o i é uma exclamação que parece muito aquela placa de cuidado, ai pensei em fazer assim:
![photo5121146939226828414](https://user-images.githubusercontent.com/52640974/93359122-9de2a000-f818-11ea-8cef-6e6892544188.jpg)

E a outra é um escudo com o plano piloto igual a UnB
![photo5121146939226828416](https://user-images.githubusercontent.com/52640974/93359219-b9e64180-f818-11ea-83a6-9cd09172a37c.jpg)

**Comment by emysdias** [comment]
#66 sugestões de botões, um quadrado com bordas pequenas
![image](https://user-images.githubusercontent.com/52640974/93359488-0df12600-f819-11ea-80f4-9219229a98f0.png)

**Comment by DanielPortods** [comment]
## Vi todas as postagens dessa issue e desenvolvi essas sugestões:

### Paleta de cores:
![AdobeColor-vamoscuidar](https://user-images.githubusercontent.com/48573556/93692971-2048b980-fad0-11ea-9882-ecc1114230d2.jpeg)
Essa paleta consiste basicamente nas cores da UnB e alguns tons mais claros das mesmas. Utilizei essa paleta como base para tudo.

### Logomarca:
![escudo](https://user-images.githubusercontent.com/48573556/93693382-7ec46680-fad5-11ea-9a1a-54594bb574ad.png)

Já havia sugerido um tipo de escudo e vi que outros integrantes sugeriram também. Essa logo serviria como fav icon, e provavelmente só apareceria pro usuário nas telas de login e cadastro. 

### Wordmark:
![wordmak](https://user-images.githubusercontent.com/48573556/93693152-5850fc00-fad2-11ea-9393-84e9931b2c5c.png)
A wordmark é uma espécie de logomarca com o nome da plataforma. Ela estaria bem presente pro usuário. Na imagem pode se ver o wordmark com as cores da paleta que podem servir de fundo. A wordmark é escrita com a fonte [Revue BT](https://br.maisfontes.com/revue-bt).

### Fonte:
Para o texto, usariamos a fonte [Roboto](https://fonts.google.com/specimen/Roboto?query=ROBOTO). Abaixo tem alguns padrões de botões com texto nessa fonte e coloridos de acordo com a paleta escolhida.
![buttons](https://user-images.githubusercontent.com/48573556/93693238-a0bce980-fad3-11ea-8e21-98152da9a1ef.png)

Também coloquei esses exemplos do que imaginei ser o ideal para a plataforma:
Topbar:
![topbar](https://user-images.githubusercontent.com/48573556/93693261-f4c7ce00-fad3-11ea-8f65-96c9dabb7fe7.png)
Navbar:
![iconbar](https://user-images.githubusercontent.com/48573556/93693263-fee9cc80-fad3-11ea-9427-26dca363e077.png)
 
Importante ressaltar que esses icones são somente ilustrativos e não necessariamente os usaremos no projeto.

**Comment by DenysRogeres** [comment]
Pensei nessa logo, seriam duas mãos, formando um "V" e ao centro viria uma um coração preenchido com a bandeira da UnB

![IMG_20200920_173752_1.jpg](https://user-images.githubusercontent.com/54676096/93721668-1b374900-fb68-11ea-9b26-9f6b965a599b.jpg)

**Comment by DenysRogeres** [comment]
Um formato genérico também pode ser feito assim: 

![IMG_20200920_175131.jpg](https://user-images.githubusercontent.com/54676096/93721991-fa6ff300-fb69-11ea-9775-94736f5cb0a0.jpg)

**Comment by DenysRogeres** [comment]
Também pensei nessa logo, aqui a ideia seria utilizar duas mãos e ao final, as duas formarem um coração. Nesse caso, utilizei verde em uma mão e azul em outra. Essa foi a logo que eu mais gostei!

![IMG_20200920_181203.jpg](https://user-images.githubusercontent.com/54676096/93722395-d661e100-fb6c-11ea-85d5-d4d11a42f5bb.jpg)

**Comment by DenysRogeres** [comment]
Essa é a última logo, a ideia aqui é duas mãos segurarem um coração preenchido com a logo da UnB. (Minha namorada quem fez)

![IMG_20200920_182318_1.jpg](https://user-images.githubusercontent.com/54676096/93722604-6b190e80-fb6e-11ea-832e-5414f8fb3cec.jpg)

**Comment by Bruno-Felix** [comment]
> Também pensei nessa logo, aqui a ideia seria utilizar duas mãos e ao final, as duas formarem um coração. Nesse caso, utilizei verde em uma mão e azul em outra. Essa foi a logo que eu mais gostei!
> 
> ![IMG_20200920_181203.jpg](https://user-images.githubusercontent.com/54676096/93722395-d661e100-fb6c-11ea-85d5-d4d11a42f5bb.jpg)

Achei interessante... Se foise só as bordas talvez ficaria bacana.E não geraria conflitos com o desing da página.

**Comment by DenysRogeres** [comment]
Aqui a logo que foi discutida na nossa daily de ontem:
![logo_vamos_cuidar](https://user-images.githubusercontent.com/54676096/93919246-c91b3280-fce3-11ea-8d90-4ca1b4161bb5.png)

**Comment by DenysRogeres** [comment]
Está aqui esta com as cores oficiais da nossa paleta 
![LogoVamosCuidar](https://user-images.githubusercontent.com/54676096/93928986-87918400-fcf1-11ea-83fd-e073890b8912.png)

**Comment by DanielPortods** [comment]
### Em reunião realizada no dia 21/09, a equipe decidiu pelo seginte conjunto de estilo:

#### Paleta de cores:
![AdobeColor-vamoscuidar](https://user-images.githubusercontent.com/48573556/94008542-902d9d00-fd79-11ea-992c-1526e97abb58.jpeg)

#### Logomaraca:
![logoVC](https://user-images.githubusercontent.com/54676096/93928986-87918400-fcf1-11ea-83fd-e073890b8912.png)

#### Wordmark:
![wordmarkVC](https://user-images.githubusercontent.com/48573556/94009506-ed761e00-fd7a-11ea-9189-fd9294ebdc11.png)

#### Fontes: [Montserrat](https://fonts.google.com/specimen/Montserrat?selection.family=Montserrat&sidebar.open=true) e [Revue BT](https://br.maisfontes.com/revue-bt) (Apenas na Wordmark).
