### ISSUE TITLE
Criar ambiente de desenvolvimento

### ISSUE THREAD

**Issue by daniel-bm** [fga-eps-mds/2020.1-VC_Usuario#72]
### Descrição:
Descrever de maneira clara e objetiva o propósito da issue.

### Tarefas:
Checklist de ações que devem ser realizadas.

- [x] Criar arquivo Dockerfile front-end;
- [x] Criar arquivo Dockerfile back-end;
- [x] Configurar Docker-compose com node;
- [x] Configurar Docker-compose com mongo;
- [x] Criar projeto Node;
- [x] Criar novo respositório.

### Critérios de aceitação:
Descrever os requisitos necessários para que a issue possa ser finalizada.

- [x] Ambiente dockerizado estar funcionando corretamente

**Comment by daniel-bm** [comment]
O monitor da disciplina enviou dois tutoriais muito interessantes [Docker com node](https://www.digitalocean.com/community/tutorials/containerizing-a-node-js-application-for-development-with-docker-compose) e [Docker com vue](https://vuejs.org/v2/cookbook/dockerize-vuejs-app.html)

**Comment by Bruno-Felix** [comment]
Criamos um Repositório Teste para auxiliar a produção do ambiente de desenvolvimento: [testeAmbiente](https://github.com/Bruno-Felix/testeAmbiente)

**Comment by Bruno-Felix** [comment]
Criar arquivo Dockerfile backend no respositório teste;

**Comment by Bruno-Felix** [comment]
Repositório Front End: [FrontEnd](https://github.com/Bruno-Felix/2020.1-VC_Usuario-FrontEnd)
