### ISSUE TITLE
Atualizar a GitHub Page

### ISSUE THREAD

**Issue by DanielPortods** [fga-eps-mds/2020.1-VC_Usuario#84]
### Descrição:
Issue destinada à atualização da página de documentação com as versões mais novas dos documentos e padronização do uso somente da branch gh-page como fonte da documentação.

### Tarefas:

- [x]  Atualizar a branch gh-page com os artefatos mais atualizados.

- [ ] remover a pasta docs da branch develop.

### Critérios de aceitação:

- [x] A página de documentação deve estar totalmente acessível.

- [x] A brach gh-pages deves ser adotada definitivamente para alterações de documentos.

**Comment by Bruno-Felix** [comment]
![Captura de tela de 2020-09-24 16-25-59](https://user-images.githubusercontent.com/38890440/94191926-a07e6e80-fe84-11ea-83f0-3b0939e74886.png)
![Captura de tela de 2020-09-24 16-42-03](https://user-images.githubusercontent.com/38890440/94192250-11258b00-fe85-11ea-98ef-81597759b1ca.png)
![Captura de tela de 2020-09-24 16-44-49](https://user-images.githubusercontent.com/38890440/94192654-a0cb3980-fe85-11ea-98c8-5fb6867c07fa.png)
![Captura de tela de 2020-09-24 16-45-38](https://user-images.githubusercontent.com/38890440/94192530-75e0e580-fe85-11ea-8e76-6418896cc4e5.png)
![Captura de tela de 2020-09-24 16-45-31](https://user-images.githubusercontent.com/38890440/94192614-927d1d80-fe85-

**Comment by Bruno-Felix** [comment]
https://www.figma.com/file/6L0LrcjiqSBTxQUXlveyJc/Vamos-Cuidar?node-id=0%3A1

**Comment by DanielPortods** [comment]
A página de documentação do projeto pode ser acessada por [aqui](https://fga-eps-mds.github.io/2020.1-VC_Usuario/).

**Comment by Bruno-Felix** [comment]
Precisa Atualizar link da GH Page no espaço About do repositório na página principal do repositório do front end e do back end:

**Comment by DanielPortods** [comment]
Atualizado!

**Comment by DanielPortods** [comment]
A remoção da pasta docs da branch develop e qualquer correção de erros será feita na próxima revisão geral de documentação.
