### ISSUE TITLE
Considerações dos documentos gerados - Políticas

### ISSUE THREAD

**Issue by mbslet** [fga-eps-mds/2020.1-VC_Usuario#88]
## Considerações dos documentos gerados - Políticas
Considerações dos documentos de políticas

### Descrição:
Oi pessoas! Estou analisando o repositorio de vocês e fazendo umas verificações no material que já foi feito, segue aqui algumas considerações.

Seria interessante, nas política de [PR](https://github.com/fga-eps-mds/2020.1-Vamos_Cuidar-Usuario/blob/develop/docs/policies/pull_request.md), 

- não deixar que um PR seja aceito sem que pelo menos duas pessoas aprovem. 

- Só aceitar o PR caso todos os critérios de aceitação sejam atendidos.

- Só aceitar o PR caso o CI rode sem erros após modificações ou funcionalidades. Isso garante várias coisas pré definidas por vocês a ser seguido durante o projeto, o código deverá estar no padrão estabelecido, seguindo uma folha de estilo, rodar os testes para que garanta sucesso, entre outros. (Isso caso vocês tenham adotado o uso de uma pipeline integrada ao projeto, o que geralmente é necessário :p )

A política de [issues](https://github.com/fga-eps-mds/2020.1-Vamos_Cuidar-Usuario/blob/develop/docs/policies/issues.md) parece bem completa, a estrutura dela está bem legal. 😀 

Estabeleceram bem o padrão de [commit](https://github.com/fga-eps-mds/2020.1-Vamos_Cuidar-Usuario/blob/develop/docs/policies/commits.md), se cobrem para seguir e no final ter tudo bem padronizado. 😀 

O sistema de [branch](https://github.com/fga-eps-mds/2020.1-Vamos_Cuidar-Usuario/blob/develop/docs/policies/branches.md) está seguindo o padrão do [gitflow](https://www.atlassian.com/br/git/tutorials/comparing-workflows/gitflow-workflow), isso é ótimo 🤩

Ao acessar o arquivo [polices.md](https://github.com/fga-eps-mds/2020.1-Vamos_Cuidar-Usuario/blob/develop/docs/policies/policies.md), os links das opções não estão redirecionando pra cada página, só para o diretório 

> /docs/policies/

Vou analisar os outros documentos, dei uma olhada por cima, caso tenha algo que interpretei errado aqui podem me dar um toque que eu vejo novamente, alguma dúvida ou coisa do tipo podem falar comigo. 😗✌️

**Comment by Bruno-Felix** [comment]
Muito obrigado @mbslet pelo seu feedback sobre nossas políticas.  

Iremos acrescentar/ resolver todos os seus pontos levantados.

## Tarefas
- [ ] Não deixar que um PR seja aceito sem que pelo menos duas pessoas aprovem.
- [ ] Só aceitar o PR caso todos os critérios de aceitação sejam atendidos.
- [ ] Só aceitar o PR caso o CI rode sem erros após modificações ou funcionalidades.
- [ ] Modificar redirecionamento dos link das opções do policies.md para os documentos que elas representam.

## Critérios de Aceitação
- [ ] Todos os pontos do PR serem devidamente acrescentados ao projeto;
- [ ] Os links das opções do policies.md estarem redirecionando para o devido documento.

**Comment by Bruno-Felix** [comment]
> Muito obrigado @mbslet pelo seu feedback sobre nossas políticas.
> 
> Iremos acrescentar/ resolver todos os seus pontos levantados.
> 
> ## Tarefas
> * [ ]  Não deixar que um PR seja aceito sem que pelo menos duas pessoas aprovem;
> * [ ]  Só aceitar o PR caso todos os critérios de aceitação sejam atendidos;
> * [ ]  Só aceitar o PR caso o CI rode sem erros após modificações ou funcionalidades;
> * [ ]  Modificar redirecionamento dos link das opções do policies.md para os documentos que elas representam;
> * [ ]  Revisar branches.md;
> * [ ]  Revisar commits.md;
> * [ ]  Revisar issues.md;
> * [ ]  Revisar pull_request.md
> 
> ## Critérios de Aceitação
> * [ ]  Todos os pontos do PR serem devidamente acrescentados ao projeto;
> * [ ]  Os links das opções do policies.md estarem redirecionando para o devido documento.

Durante uma passagem rápida pelos documentos, percebi que nem todos seguem o padrão aplicado, na prática, pelo grupo. Logo revisar todas as os documentos das politicas e seus certos pontos é necessário.

**Comment by emysdias** [comment]
> ## Título da issue
> 
> Considerações dos documentos de políticas
> ### Descrição:
> 
> Oi pessoas! Estou analisando o repositorio de vocês e fazendo umas verificações no material que já foi feito, segue aqui algumas considerações.
> 
> Seria interessante, nas política de [PR](https://github.com/fga-eps-mds/2020.1-Vamos_Cuidar-Usuario/blob/develop/docs/policies/pull_request.md),
> 
>     * não deixar que um PR seja aceito sem que pelo menos duas pessoas aprovem.
> 
>     * Só aceitar o PR caso todos os critérios de aceitação sejam atendidos.
> 
>     * Só aceitar o PR caso o CI rode sem erros após modificações ou funcionalidades. Isso garante várias coisas pré definidas por vocês a ser seguido durante o projeto, o código deverá estar no padrão estabelecido, seguindo uma folha de estilo, rodar os testes para que garanta sucesso, entre outros. (Isso caso vocês tenham adotado o uso de uma pipeline integrada ao projeto, o que geralmente é necessário :p )
> 
> 
> A política de [issues](https://github.com/fga-eps-mds/2020.1-Vamos_Cuidar-Usuario/blob/develop/docs/policies/issues.md) parece bem completa, a estrutura dela está bem legal. grinning
> 
> Estabeleceram bem o padrão de [commit](https://github.com/fga-eps-mds/2020.1-Vamos_Cuidar-Usuario/blob/develop/docs/policies/commits.md), se cobrem para seguir e no final ter tudo bem padronizado. grinning
> 
> O sistema de [branch](https://github.com/fga-eps-mds/2020.1-Vamos_Cuidar-Usuario/blob/develop/docs/policies/branches.md) está seguindo o padrão do [gitflow](https://www.atlassian.com/br/git/tutorials/comparing-workflows/gitflow-workflow), isso é ótimo star_struck
> 
> Ao acessar o arquivo [polices.md](https://github.com/fga-eps-mds/2020.1-Vamos_Cuidar-Usuario/blob/develop/docs/policies/policies.md), os links das opções não estão redirecionando pra cada página, só para o diretório
> 
> > /docs/policies/
> 
> Vou analisar os outros documentos, dei uma olhada por cima, caso tenha algo que interpretei errado aqui podem me dar um toque que eu vejo novamente, alguma dúvida ou coisa do tipo podem falar comigo. kissingv

massa muito obrigada pelos feedbacks

**Comment by daniel-bm** [comment]
Muito obrigado pelo feedback

**Comment by DenysRogeres** [comment]
> ## Título da issue
> Considerações dos documentos de políticas
> 
> ### Descrição:
> Oi pessoas! Estou analisando o repositorio de vocês e fazendo umas verificações no material que já foi feito, segue aqui algumas considerações.
> 
> Seria interessante, nas política de [PR](https://github.com/fga-eps-mds/2020.1-Vamos_Cuidar-Usuario/blob/develop/docs/policies/pull_request.md),
> 
> * não deixar que um PR seja aceito sem que pelo menos duas pessoas aprovem.
> * Só aceitar o PR caso todos os critérios de aceitação sejam atendidos.
> * Só aceitar o PR caso o CI rode sem erros após modificações ou funcionalidades. Isso garante várias coisas pré definidas por vocês a ser seguido durante o projeto, o código deverá estar no padrão estabelecido, seguindo uma folha de estilo, rodar os testes para que garanta sucesso, entre outros. (Isso caso vocês tenham adotado o uso de uma pipeline integrada ao projeto, o que geralmente é necessário :p )
> 
> A política de [issues](https://github.com/fga-eps-mds/2020.1-Vamos_Cuidar-Usuario/blob/develop/docs/policies/issues.md) parece bem completa, a estrutura dela está bem legal. 
> 
> Estabeleceram bem o padrão de [commit](https://github.com/fga-eps-mds/2020.1-Vamos_Cuidar-Usuario/blob/develop/docs/policies/commits.md), se cobrem para seguir e no final ter tudo bem padronizado. 
> 
> O sistema de [branch](https://github.com/fga-eps-mds/2020.1-Vamos_Cuidar-Usuario/blob/develop/docs/policies/branches.md) está seguindo o padrão do [gitflow](https://www.atlassian.com/br/git/tutorials/comparing-workflows/gitflow-workflow), isso é ótimo 
> 
> Ao acessar o arquivo [polices.md](https://github.com/fga-eps-mds/2020.1-Vamos_Cuidar-Usuario/blob/develop/docs/policies/policies.md), os links das opções não estão redirecionando pra cada página, só para o diretório
> 
> > /docs/policies/
> 
> Vou analisar os outros documentos, dei uma olhada por cima, caso tenha algo que interpretei errado aqui podem me dar um toque que eu vejo novamente, alguma dúvida ou coisa do tipo podem falar comigo.

Muito obrigado @mbslet, ajudou demaais!
