### ISSUE TITLE
Considerações dos documentos gerados - Documentos do projeto

### ISSUE THREAD

**Issue by mbslet** [fga-eps-mds/2020.1-VC_Usuario#92]
### Descrição:

No [Documento de Visão](https://github.com/fga-eps-mds/2020.1-Vamos_Cuidar-Usuario/blob/develop/docs/Documento_de_Visao.md):

- No tópico 3.2 Resumo dos Usuários, a funcionalidade vai funcionar da mesma forma para todos aqueles diferentes tipo de usuário?

- No tópico 3.4 Ambiente dos Usuários, o que querem dizer com "Os usuários poderão **realizar** a aplicação Vamos Cuidar"?

No geral o documento de visão está bem completo de acordo com as referências utilizadas, contém o necessário e explica bem o produto.

No [Documento de Arquitetura](https://github.com/fga-eps-mds/2020.1-Vamos_Cuidar-Usuario/blob/develop/docs/Documento_de_arquitetura.md) senti falta de diagramas para especificar melhor cada ponto, vi que tem os campos sem conteúdo, presumo que ainda vão fazer, ajuda muito na compreensão do projeto e na integração entre sistemas.

- No tópico 4.2 Atores de Casos de Uso, mostra como ator apenas um tipo de usuário. No contexto da aplicação de vocês vai ter apenas um usuário que só submete uma comunicação? Ou vão tratar também o usuário sendo professor, que recebe essa comunicação e faz alguma ação? Minha dúvida ficou em se todos os integrantes da universidade vão ter o mesmo papel na aplicação, com o mesmo fluxo.

Sei que o documento ainda não foi finalizado, procurem finalizar o quanto antes pois um escopo bem definido e documentado facilita no desenvolvimento. Incluam diagramas de pacotes, componentes, estados. Isso vai auxiliar não só quem vê a aplicação de fora, mas também a vocês compreenderem bem o fluxo da aplicação que deverá ser seguida.

O [Plano de Riscos](https://github.com/fga-eps-mds/2020.1-Vamos_Cuidar-Usuario/blob/develop/docs/Plano_riscos.md) parece muito bom, parabéns! O levantamento de riscos já trata futuros impecílios, segue boas referências também. 😊

O [Backlog](https://github.com/fga-eps-mds/2020.1-Vamos_Cuidar-Usuario/blob/develop/docs/Product_Backlog.md) parece bem completo 😊

Acho válido que no [Roadmap](https://github.com/fga-eps-mds/2020.1-Vamos_Cuidar-Usuario/blob/develop/docs/Roadmap.md) coloquem uma coluna para **dívidas**, referente a possíveis divídas técnicas da sprint.  Adicionem também os pareamentos definidos para o desenvolvimento de cada história de usuário.

**Comment by mbslet** [comment]
@Bruno-Felix @daniel-bm @emysdias @enzoggqs @DenysRogeres @DanielPortods

**Comment by emysdias** [comment]
> ## Título da issue
> 
> Considerações dos documentos gerados - Documentos do projeto
> ### Descrição:
> 
> No [Documento de Visão](https://github.com/fga-eps-mds/2020.1-Vamos_Cuidar-Usuario/blob/develop/docs/Documento_de_Visao.md):
> 
>     * No tópico 3.2 Resumo dos Usuários, a funcionalidade vai funcionar da mesma forma para todos aqueles diferentes tipo de usuário?
> 
>     * No tópico 3.4 Ambiente dos Usuários, o que querem dizer com "Os usuários poderão **realizar** a aplicação Vamos Cuidar"?
> 
> 
> No geral o documento de visão está bem completo de acordo com as referências utilizadas, contém o necessário e explica bem o produto.
> 
> No [Documento de Arquitetura](https://github.com/fga-eps-mds/2020.1-Vamos_Cuidar-Usuario/blob/develop/docs/Documento_de_arquitetura.md) senti falta de diagramas para especificar melhor cada ponto, vi que tem os campos sem conteúdo, presumo que ainda vão fazer, ajuda muito na compreensão do projeto e na integração entre sistemas.
> 
>     * No tópico 4.2 Atores de Casos de Uso, mostra como ator apenas um tipo de usuário. No contexto da aplicação de vocês vai ter apenas um usuário que só submete uma comunicação? Ou vão tratar também o usuário sendo professor, que recebe essa comunicação e faz alguma ação? Minha dúvida ficou em se todos os integrantes da universidade vão ter o mesmo papel na aplicação, com o mesmo fluxo.
> 
> 
> Sei que o documento ainda não foi finalizado, procurem finalizar o quanto antes pois um escopo bem definido e documentado facilita no desenvolvimento. Incluam diagramas de pacotes, componentes, estados. Isso vai auxiliar não só quem vê a aplicação de fora, mas também a vocês compreenderem bem o fluxo da aplicação que deverá ser seguida.
> 
> O [Plano de Riscos](https://github.com/fga-eps-mds/2020.1-Vamos_Cuidar-Usuario/blob/develop/docs/Plano_riscos.md) parece muito bom, parabéns! O levantamento de riscos já trata futuros impecílios, segue boas referências também. blush
> 
> O [Backlog](https://github.com/fga-eps-mds/2020.1-Vamos_Cuidar-Usuario/blob/develop/docs/Product_Backlog.md) parece bem completo blush
> 
> Acho válido que no [Roadmap](https://github.com/fga-eps-mds/2020.1-Vamos_Cuidar-Usuario/blob/develop/docs/Roadmap.md) coloquem uma coluna para **dívidas**, referente a possíveis divídas técnicas da sprint. Adicionem também os pareamentos definidos para o desenvolvimento de cada história de usuário.

Beleza, obrigadaaa pelas informações

**Comment by DanielPortods** [comment]
Desde já, agradeçemos a sua ajuda, @mbslet . 
Sobre o doc de arquitetura, o @enzoggqs e eu estamos o revisando nessa Sprint de acordo com a demanda da professora. Temos um recente pr aberto sobre isso. 
No que diz respeito ao tópico 4.2, na versão atual falta o diagrama do tópico 4.1 que mostra os dois tipos de usuários (estudante e servidor) e complementa o entendimento do tópico dos casos de uso. 
Na versão que está aguardando revisão, já estão presentes alguns diagramas de representações arquiteturais. Nessa nova versão fica explícito que toda a plataforma possui duas frentes de desenvolvimento, dashboard (vcg), e o cliente (vcu).
Na nossa frente (vcu), trabalhamos apenas com esses dois tipos de users, os quais terão papel e fluxo em comum.

**Comment by Bruno-Felix** [comment]
@mbslet, no tópico 3.2, sim a funcionalidade vai funcionar da mesma forma para todos aqueles diferentes tipo de usuário.

A intenção era explicar que qualquer pessoa poderia usar a aplicação.

Você acredita que deixar essa descrição mais genérica como: "Todos os membros pertencentes a Universidade de Brasília" pararia de gerar essa dúvida?

**Comment by Bruno-Felix** [comment]
## Tarefas
- [ ] Revisar Tópico 3.2 do Documento de Visão;
- [ ] Revisar Tópico 3.4 do Documento de Visão.

## Critério de Aceitação
- [ ] Todos os pontos levantados sere devidamente revisados.

**Comment by DenysRogeres** [comment]
> ## Título da issue
> Considerações dos documentos gerados - Documentos do projeto
> 
> ### Descrição:
> No [Documento de Visão](https://github.com/fga-eps-mds/2020.1-Vamos_Cuidar-Usuario/blob/develop/docs/Documento_de_Visao.md):
> 
> * No tópico 3.2 Resumo dos Usuários, a funcionalidade vai funcionar da mesma forma para todos aqueles diferentes tipo de usuário?
> * No tópico 3.4 Ambiente dos Usuários, o que querem dizer com "Os usuários poderão **realizar** a aplicação Vamos Cuidar"?
> 
> No geral o documento de visão está bem completo de acordo com as referências utilizadas, contém o necessário e explica bem o produto.
> 
> No [Documento de Arquitetura](https://github.com/fga-eps-mds/2020.1-Vamos_Cuidar-Usuario/blob/develop/docs/Documento_de_arquitetura.md) senti falta de diagramas para especificar melhor cada ponto, vi que tem os campos sem conteúdo, presumo que ainda vão fazer, ajuda muito na compreensão do projeto e na integração entre sistemas.
> 
> * No tópico 4.2 Atores de Casos de Uso, mostra como ator apenas um tipo de usuário. No contexto da aplicação de vocês vai ter apenas um usuário que só submete uma comunicação? Ou vão tratar também o usuário sendo professor, que recebe essa comunicação e faz alguma ação? Minha dúvida ficou em se todos os integrantes da universidade vão ter o mesmo papel na aplicação, com o mesmo fluxo.
> 
> Sei que o documento ainda não foi finalizado, procurem finalizar o quanto antes pois um escopo bem definido e documentado facilita no desenvolvimento. Incluam diagramas de pacotes, componentes, estados. Isso vai auxiliar não só quem vê a aplicação de fora, mas também a vocês compreenderem bem o fluxo da aplicação que deverá ser seguida.
> 
> O [Plano de Riscos](https://github.com/fga-eps-mds/2020.1-Vamos_Cuidar-Usuario/blob/develop/docs/Plano_riscos.md) parece muito bom, parabéns! O levantamento de riscos já trata futuros impecílios, segue boas referências também. 
> 
> O [Backlog](https://github.com/fga-eps-mds/2020.1-Vamos_Cuidar-Usuario/blob/develop/docs/Product_Backlog.md) parece bem completo 
> 
> Acho válido que no [Roadmap](https://github.com/fga-eps-mds/2020.1-Vamos_Cuidar-Usuario/blob/develop/docs/Roadmap.md) coloquem uma coluna para **dívidas**, referente a possíveis divídas técnicas da sprint. Adicionem também os pareamentos definidos para o desenvolvimento de cada história de usuário.

Brigadããão @mbslet ! Sensacional. Fiquei com um dúvida, eu posso deslocar essa parte das **dívidas técnicas** na review da Sprint? Acredito que pela documentação da Sprint Review ser semanal, ficará mais sucinto.
