### ISSUE TITLE
Definição de termos e variáveis

### ISSUE THREAD

**Issue by Mateusas3s** [fga-eps-mds/2020.1-VC_Usuario#95]
### Descrição:
Teremos de definir alguns termos para definir alguns objetos, para que tenhamos uma linguagem em comum, e quais as variáveis que compõem esses objetos. Isso facilitará quando cada aplicação requisitar as informações necessárias

Segue um documento para definição de [Objetos e variáveis](https://docs.google.com/document/d/1F18uFf8L4_CnApd5SjSpE6aW17Jmk7HbsdCfyTSGvAk/edit?usp=sharing) do projeto

**Para manter um controle:**
- **comentários em vermelho VCG**
- **comentários em verde VCG**

### Tarefas:
Checklist de ações que devem ser realizadas.

- [x] Definir termos dos objetos e variáveis que os compoem 
- [x] Definir elementos do objeto recuperado pelo VCG
- [x] Definir elementos do objeto recuperado pelo VCU

### Critérios de aceitação:
Descrever os requisitos necessários para que a issue possar ser finalizada.

- [x] Validar isso com os dois times

**Comment by Mateusas3s** [comment]
Dei uma olhada no doc de arquitetura de vocês, em específico na modelagem das classes e fiquei com alguns questionamentos. Eles estão  relatados no documento da referência

**Comment by DanielPortods** [comment]
Fiz alguns comentários no documento disponibilizado.

**Comment by Mateusas3s** [comment]
Está adicionado também os dados que vamos requisitar da sua aplicação

**Comment by Mateusas3s** [comment]
Pontuei lá no documento sobre os atributos data e hora, que podem ser unidos.
E falei também sobre o atributo grau de relevância, que não precisa armazenar no banco.

**Comment by DanielPortods** [comment]
Obrigado pela comunicação! Acredito que está tudo certo. Não hesitem em questionar nossa equipe no que for preciso! 
👍🏽

**Comment by Bruno-Felix** [comment]
@Mateusas3s, tem algo a mais para debatermos?

**Comment by Mateusas3s** [comment]
agora só falta passarmos a descrição dos atributos do objeto notícias e benefícios, mas isso fica pra resolvermos numa issue futura.
